import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/features/header'
import { UiBgMain } from '@/shared/ui/ui-bg-main'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Netflix clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="uk">
      <body className={inter.className}>
        <UiBgMain>
          <Header />
          {children}
        </UiBgMain>
      </body>
    </html>
  )
}
